"""FCIL-AndroidMalware Configuration Package."""

from .config import (
    ScenarioConfig,
    ModelConfig,
    FLConfig,
    IncrementalConfig,
    ILConfig,
    ExperimentConfig,
    task_config,
    STATIC_LABEL_MAP,
    DYNAMIC_LABEL_MAP,
    get_task_label_map,
    get_cumulative_labels,
    get_label_to_task_mapping,
    save_config,
    load_config,
)

from .task_config import (
    TASK_LABEL_MAP,
    ALL_LABELS,
    LABEL_TO_IDX,
    IDX_TO_LABEL,
    LABEL2ID,
    ID2LABEL,
    TASK_TO_INDICES,
    LABEL_TO_TASK,
    get_labels_for_task,
    get_indices_for_task,
    get_cumulative_labels as get_task_cumulative_labels,
    get_cumulative_indices,
    get_num_classes_for_task,
    get_task_for_label,
    is_label_in_task,
    get_client_counts,
    STATIC_FEATURE_DIM,
    DYNAMIC_FEATURE_DIM,
    FUSED_FEATURE_DIM,
    MIN_SAMPLES_PER_LABEL_CLIENT,
    DEFAULT_BATCH_SIZE,
    FEDERATED_BATCH_SIZE,
    CENTRALIZED_BATCH_SIZE,
    get_batch_size_for_mode,
)

from .paths import (
    PathBuilder,
    get_project_root,
    get_default_data_root,
    get_default_checkpoint_root,
    get_default_log_root,
)

__all__ = [
    # Config classes
    'ScenarioConfig',
    'ModelConfig',
    'FLConfig',
    'IncrementalConfig',
    'ILConfig',
    'ExperimentConfig',
    # Config data
    'task_config',
    'STATIC_LABEL_MAP',
    'DYNAMIC_LABEL_MAP',
    # Task config
    'TASK_LABEL_MAP',
    'ALL_LABELS',
    'LABEL_TO_IDX',
    'IDX_TO_LABEL',
    'LABEL2ID',
    'ID2LABEL',
    'TASK_TO_INDICES',
    'LABEL_TO_TASK',
    'STATIC_FEATURE_DIM',
    'DYNAMIC_FEATURE_DIM',
    'FUSED_FEATURE_DIM',
    'MIN_SAMPLES_PER_LABEL_CLIENT',
    'DEFAULT_BATCH_SIZE',
    'FEDERATED_BATCH_SIZE',
    'CENTRALIZED_BATCH_SIZE',
    # Functions
    'get_task_label_map',
    'get_cumulative_labels',
    'get_label_to_task_mapping',
    'get_labels_for_task',
    'get_indices_for_task',
    'get_task_cumulative_labels',
    'get_cumulative_indices',
    'get_num_classes_for_task',
    'get_task_for_label',
    'is_label_in_task',
    'get_client_counts',
    'get_batch_size_for_mode',
    'save_config',
    'load_config',
    # Paths
    'PathBuilder',
    'get_project_root',
    'get_default_data_root',
    'get_default_checkpoint_root',
    'get_default_log_root',
]
